apiVersion: v1
kind: Secret
metadata:
  name: fintech-secret
  namespace: fintech

type: Opaque

data:
  JWT_SECRET: bXlzZWNyZXRrZXk=
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: cGFzc3dvcmQxMjM=
  POSTGRES_USERNAME: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=
  